### ISSUE TITLE
Huh?

### ISSUE THREAD

**Issue by jbrooksuk** [michaelshobbs/dokku-hostname#1]
Could you explain a little bit more about what exactly this plugin does and how it works please?

**Comment by michaelshobbs** [comment]
It's just a quick hack to set the container hostname to match the host. I use this to allow NewRelic to aggregate stats between deployments. With the default behavior you end up with a new hostname every deploy.

**Comment by jbrooksuk** [comment]
So all I need to do is install the plugin and the hostname will match? That's the behaviour I'm after.

**Comment by michaelshobbs** [comment]
That is correct.
